### PR TITLE
Issue #1457 - Allow Example Resource to Load

### PR DESCRIPTION
**Pull request by jasonrahm**
Problem: the example file is a collection kind, which is a kind
         mismatch on a resource

Solution: Check for example at end of selflink in the _produce_instance
          def and don't error on kind mismatch if present

Files Changed:

 - f5/bigip/resource.py

### CODE REVIEW

**Comment by jasonrahm** [comment]
don't merge yet, even if the build passes I want to add a unit test for a positive match for an example

**Comment by jasonrahm** [comment]
ready for review, @caphrim007 or @wojtek0806

**Comment by caphrim007** [comment]
this looks fine

**Comment by wojtek0806** [comment]
approved

**Review by wojtek0806 — COMMENTED** [review]
approved

**Pull request merged**
