### PR TITLE
Trust Domain - tests failing in 12.1

### PR DESCRIPTION
**Pull request by jasonrahm**
Updated File:
- f5/bigip/tm/cm/trust_domain.py
- test/functional/cm/test_trust_domain.py
  
  Added File:
- f5/bigip/tm/cm/test/test_trust_domain.py

Updates:
- Added unit tests
- Trust Domain never intended to allow create/delete, adding error handlers to prevent their use
- Fixed functional tests given added create/delete restrictions on this resource

### CODE REVIEW

**Comment by jasonrahm** [comment]
Note that the create/delete methods will raise an unsupported message for all versions, not just 12.1.

**Comment by pjbreaux** [comment]
You may also want to check out the clustering module in multi_device, as it uses trust_domain create and delete, I believe.

**Comment by jasonrahm** [comment]
ok will do

**Comment by jasonrahm** [comment]
ok, all cluster tests were not impacted, I think the multi-device "trust domain" is not the same as the iControl REST interface cm/trust-domain.

This is ready for review @caphrim007

**Comment by caphrim007** [comment]
lgtm. @pjbreaux any concerns?

**Pull request merged**
