### PR TITLE
Ltm.profiles

### LINKED ISSUE #349: Add LTM profile creation
As for now the SDK does not allow for creation of profiles. SDK needs to provide the ability to create profiles for LTM.

### PR DESCRIPTION
**Pull request by wojtek0806**
Fixes #349, #341

This update introduces profile submodule to LTM, allowing to create LTM classes.

Problem: SDK did not have the APIs to create LTM profiles, this change has addressed that

Analysis: Introduced new profile.py sub-module which incorporated majority of LTM profiles.

CAVEAT: Ramcache, and wa-cache profiles have placeholder classes and are not implemented due to some issues I was having with matching tmsh syntax to REST. This needs further investigation with Product Development

Tests:
Unit Tests
Flake8
Functional Tests

### CODE REVIEW

**Comment by wojtek0806** [comment]
@zancas 
Please review as this update will overwrite your profile.py, which has been merged yesterday. Like i mentioned in the closed ticket my work has been again duplicated

**Comment by wojtek0806** [comment]
@zancas There is a problem in your change, You have removed 
''''
self._meta_data['allowed_lazy_attributes']
''''
Which breaks this badly. Entire list self._meta_data['allowed_lazy_attributes'] has been removed only containing Client_Ssls entry. Please fix

**Comment by wojtek0806** [comment]
Also as far as I can see each organizing collection contains the allowed_lazy_attributes list.

**Comment by wojtek0806** [comment]
@zancas 

I have looked at your new testing for client SSL, and reworked your coding, it should be backwards compatible with what you did and at the same time not break the convention we are using in the SDK. Your old solution was deviating from it and that would cause unnecessary problems. Also your usage of 'key', 'cert' the way you had is depricated, and utilizing 'certKeyChain' array is preffered, which is what the below addresses too. I cannot seem to run your test for client_ssl so can you please verify the below locally, and if all OK i will push this to my fork and we can start merging:

```

class Client_Ssl(Resource):
    def __init__(self, client_ssls):
        super(Client_Ssl, self).__init__(client_ssls)
        self._meta_data['required_json_kind'] =\
            'tm:ltm:profile:client-ssl:client-sslstate'

    def create(self, **kwargs):
        """Allows creation of SSL profile with just key/cert names
        otherwise it will just require 'name' kwarg to be provided
        """
        if 'certname' and 'keyname' in kwargs:
            kwargs['name'] = kwargs['certname'][:-4]
            kwargs['certKeyChain'] =\
                [{'cert': kwargs['certname'], 'key': kwargs['keyname']}]

        self._create(**kwargs)
        return self

```

**Comment by wojtek0806** [comment]
This addresses #49

**Comment by wojtek0806** [comment]
My mistake i reworked the code, forgot about the kwargs removal :)

```
        if 'certname' and 'keyname' in kwargs:
            certname = kwargs.pop('certname')
            keyname = kwargs.pop('keyname')
            kwargs['name'] = certname[:-4]
            kwargs['certKeyChain'] =\
                [{'cert': certname, 'key': keyname}]
```

**Comment by zancas** [comment]
'`allowed_lazy_attributes`' is a different variable than '`attribute_registry`' it would be a nice enhancement to make those two names more distinct.

**Comment by wojtek0806** [comment]
allowed_lazy_attributes is a part of organizing collections in the code, and I have checked my coding and you have removed:

self._meta_data['allowed_lazy_attributes']

from profiles class, which disabled my profile classes :)

**Comment by zancas** [comment]
Oops..

you're right I'll add that back.

**Comment by wojtek0806** [comment]
closing this PR changes will be pushed via rebased branch

**Pull request closed without merging**
