### PR TITLE
Fixing exclusive attributes bug in the Virtual Server resource

### PR DESCRIPTION
**Pull request by jasonrahm**
Notified of this issue on an article on DC. Simple fix in this file:

f5/bigip/tm/ltm/virtual_server.py

### CODE REVIEW

**Comment by jasonrahm** [comment]
@caphrim007 given we have a solution for boolean pairs, and it's been implemented on the endpoint this resource unit test was pointing to, is the unit test that's failing even useful here?

**Comment by jasonrahm** [comment]
this is ready for review, @caphrim007

**Comment by caphrim007** [comment]
Ansible modules need to be verified

**Comment by jasonrahm** [comment]
Probably should account for vlansEnabled / vlansDisabled as well for exclusive attributes, that wasn't asked about but is present on that object.

**Comment by caphrim007** [comment]
verified that the Ansible modules run without issue

**Comment by caphrim007** [comment]
ansible still works

**Pull request merged**
