### PR TITLE
# Update functional tests to reference mgmt_root instead of bigip

### LINKED ISSUE #1334: Convert all functional tests from bigip to mgmt_root
many old functional tests still reference the bigip object instead of mgmt_root.

### PR DESCRIPTION
**Pull request by jasonrahm**
Issues:
Fixes #1334

Problem: Many old tests still reference the bigip object.

Analysis: Refactored all functional tests that use the bigip object to use the mgmt_root object instead

### CODE REVIEW

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build succeeded.

**Comment by jasonrahm** [comment]
i'll squash commits and resubmit shortly

**Comment by caphrim007** [comment]
Can't set status; build succeeded.

**Comment by jasonrahm** [comment]
ready for review, @caphrim007 or @wojtek0806

**Comment by caphrim007** [comment]
lgtm

**Pull request merged**
