### PR TITLE
Issue #717 - Fixing auth functional test

### PR DESCRIPTION
**Pull request by jasonrahm**
Updated Files
- test/functional/auth/test_user.py
  
  Updates include:
  - Changed the assertions to be acceptable to all existing versions for the partitionAccess attribute
  - Converted the tests from the bigip fixture to the mgmt_root fixture

### CODE REVIEW

**Comment by jasonrahm** [comment]
@caphrim007 this one is ready for review. Passes on all my local versions, particularly on 12.1 where the original version did not.

**Comment by caphrim007** [comment]
@jasonrahm erm, lemme re-enable 12.1 tests so you can check that the error isnt in the output. i disabled in for pjbreaux's other one. i'll bounce this pr.

**Comment by caphrim007** [comment]
@jasonrahm we know this is going to fail because 12.1.0 will fail for other tests. just verify that the test you fixed no longer shows up.

**Comment by jasonrahm** [comment]
sounds good.

**Comment by jasonrahm** [comment]
one less failure occurring and this test no longer matches, so appears to have solved the issue.

**Comment by caphrim007** [comment]
lgtm. merging

**Pull request merged**
