### PR TITLE
 Adds Signature Statuses Endpoint - Merge after PR #752

### PR DESCRIPTION
**Pull request by wojtek0806**
Issues:  #705

Problem:
Sixth of the ASM PR series, this PR has to be merged after PR #752.

Analysis:
Adds Signature Statuses ASM endpoint with functional and unit tests.

Tests:
Unit Tests
Flake8
Functional Tests

### CODE REVIEW

**Comment by wojtek0806** [comment]
@zancas @caphrim007 @jasonrahm

**Comment by caphrim007** [comment]
@wojtek0806 next

**Comment by wojtek0806** [comment]
@caphrim007 done

**Comment by caphrim007** [comment]
@wojtek0806 curious why the use of `UnsupportedOperation` instead of `UnsupportedMethod` ??

**Pull request merged**
