### PR TITLE
Issues: 933

### LINKED ISSUE #933: Update RPM/DEB package dependencies
Both the `six` and the `ordereddict` modules are missing in the specifications for these two types of builds.

This results in a f5-sdk build break.

### PR DESCRIPTION
**Pull request by ssorenso**
Fixes #933

Problem:
This fixes the fact that the .rpm's and .deb's are not fully tested
prior to being released.

Analysis:
This testing will determine what the dependencies are, install them on a clean
Docker container, and have the packages installed to verify that they are
created properly and will install with the listed dependencies.

Tests:
This is a test in and of itself; however, to properly determine wether
or not this is executing properly would be to run the .travis.yml file
in its typical runtimes.

### CODE REVIEW

**Comment by ssorenso** [comment]
In order to remain consistent between this and the agent branch, I've made a few additional changes to the commit.  This will make it so that the tests are executed from the command line cleanly once the docker image is created.  I also made the `test_install.sh` script reflect the agent by making it more usable with a barebones help statement that causes a clean exit with `exit(1)` upon failure to:

- Provide a OS type
- Provide a OS version
- Provide a package name

This script was also expanded to provide a 4th `--debug` option, which allows one to have the output of the docker's fetch script to be piped into a `/tmp/test_install.o` file.  This can be helpful down the road in troubleshooting why the install test fails.

**Comment by wojtek0806** [comment]
closing and reopening to bounce jenkins

**Comment by wojtek0806** [comment]
@ssorenso 

would you mind squashing the commits please? would be easier to review

**Comment by wojtek0806** [comment]
looks good to me..

**Pull request merged**
