### PR TITLE
Added f5.bigip.resource.Stats to the list of allowed_lazy_attributes …

### PR DESCRIPTION
**Pull request by buzz-tee**
…on f5.big.tm.ltm collection objects Nodes, Pools, Rules, Virtuals and Virtual_Address_s

This is to allow obtaining all item stats with a single request which may come in handy when stats on large collections are required and calling item.stats.load() in a loop causes massive REST calls and huge delay.
Note that entries have to be mapped by the application, suggested criteria are item.fullPath and stat_entry['nestedStats']['entries']['tmName']['description'].

### CODE REVIEW

**Comment by buzz-tee** [comment]
Travis build error from upstream files, not included in PR.
Kindly asking for merge anyway.

**Comment by caphrim007** [comment]
@BastiG this needs tests.

**Comment by buzz-tee** [comment]
Provided tests as requested. Build errors are not related to PR files.

**Comment by caphrim007** [comment]
@BastiG I've fixed those build errors in a recent push. can you rebase your PR and update it here for CI/CD to try again?

**Comment by caphrim007** [comment]
@BastiG earlier, I spoke before the patch was actually in. now it is. feel free to re-base on top of latest devel and I'll merge after it passes tests

**Comment by buzz-tee** [comment]
Thanks, @caphrim007. I integrated the changes from upstream and build tests now succeed.
However all merged commits now show up in the PR, so I'll set up a fresh fork and PR there.

**Pull request closed without merging**
