### PR TITLE
Feature.clustering 5

### PR DESCRIPTION
**Pull request by pjbreaux**
@zancas 
#### What's this change do?

Implements the first bare features of BigIP clustering and scaling.
#### Any background context?

There is a need to cluster multiple BigIP devices (>=2 to <=8) with two basic cluster types ('sync-only', 'sync-failover'). This is the first basic features of that functionality. There are a few additional structures that have been added here. One important one is the f5/cluster directory, which holds the handlers for managing a cluster, device_group, and trusted_peers. These modules are simply wrappers around BigIP resource command (cm.device_groups.device_group) to control the order and timing of clustering.
#### Where should the reviewer start?

Start at the single functional test for 'sync-failover' and then move on to the f5/cluster/**init**.py. After that, you can look at the trusted_peer_manager.py and the device_group_manager.py in the managers module. I have included some interesting unit tests here as well. Mostly those that excite all the exceptions I intentionally raise.

To run the functional tests, you'll need to create at least three BigIPs. Come talk to me or sanaz.

### CODE REVIEW

**Comment by pjbreaux** [comment]
@szakeri: Please make a PR to my feature branch listed above for merging our functional tests together. Thanks!

**Comment by pjbreaux** [comment]
So the unit tests take a great deal longer than they used to and it's my fault. I'd like to talk to you @zancas about mocking out the pollster, since it is a decorator. Either that, or dropping the attempts down to 1 for every time it wants to poll.

**Comment by zancas** [comment]
@pjbreaux release has moved-beneath-you!  Please fetch/merge/rebase ASAP!

**Comment by pjbreaux** [comment]
Closing this, as it is supplanted by PR #440

**Pull request closed without merging**
