### PR TITLE
Fixes Issue #1323 - exists method failing on GTM topology records

### PR DESCRIPTION
**Pull request by jasonrahm**
Problem: The / and ~ characters are disallowed in sdk URLs

Resolution: Overload the exists method for topology by applying:
  kwargs['transform_name'] = True

### CODE REVIEW

**Comment by caphrim007** [comment]
Can't set status; build succeeded.

**Comment by jasonrahm** [comment]
hold off on merge until I hear back from the bug reporter that the fix works for him. I confirmed the behavior and the fix locally, but want to make sure.

**Comment by jasonrahm** [comment]
@caphrim007 this fixes the problem, but also allows the partition kwarg but likely should not for topology records. Should I pop that kwarg if applied to guard against unintentional issues?

**Comment by caphrim007** [comment]
@jasonrahm yes. If this changes in the future we can address it with a version check

**Comment by jasonrahm** [comment]
ok, I'll add that and push later. Thanks

**Comment by caphrim007** [comment]
Can't set status; build succeeded.

**Comment by jasonrahm** [comment]
@caphrim007 ready for review

**Comment by caphrim007** [comment]
Can't set status; build succeeded.

**Pull request merged**
