### PR TITLE
The skipped tests of #509 had aliases

### PR DESCRIPTION
**Pull request by zancas**
@caphrim007 
Issues:
Fixes #509

Problem: test_pool.py was being skipped.  Tests were failing because
of aliasing.   I've fixed the aliasing issues after applying @caphrim007s
removal of the skip.

Analysis: These tests should be run!

Tests: test/functional/tm/ltm/test_pool.py

### CODE REVIEW

**Comment by zancas** [comment]
@caphrim007 the tests passed!

**Comment by zancas** [comment]
I think this'll be good for coveralls.

**Comment by zancas** [comment]
@caphrim007 can you merge this?

**Comment by zancas** [comment]
@pjbreaux can you merge this?

**Comment by pjbreaux** [comment]
Can do. Looks good.

**Pull request merged**
