### PR TITLE
Adds properties method 

### PR DESCRIPTION
**Pull request by wojtek0806**
this is just a draft, and probably will need to have it changed slightly for python3. Tell me if this is what you are looking for @caphrim007

### CODE REVIEW

**Comment by caphrim007** [comment]
All I was doing in the meantime was running to_dict() and then doing a pop('_meta_data', None). I think the function needs a name like attrs or something like that. no_meta, while true, is also not necessarily the purpose of the method.

The use case is that I was to get all of the things that would be considered attributes of the resource if I were to do a normal curl of the endpoint.

**Comment by wojtek0806** [comment]
So you like the solution? 

For name of method maybe properties?

**Comment by caphrim007** [comment]
I think properties is fine

**Comment by wojtek0806** [comment]
this will fail for 2.6 python as we use dict comprehension. Since we are about to drop python 2.6 support from Travis, I am going to merge this regardless

**Pull request merged**
