### PR TITLE
Adds more python3 compat fixes

### PR DESCRIPTION
**Pull request by caphrim007**
Issues:
More PRs for 654

Problem:
python3 compat problems

Analysis:
patch adds more fixes for python3

Tests:
unit
functional

### CODE REVIEW

**Comment by caphrim007** [comment]
@wojtek0806 or @jasonrahm

**Comment by caphrim007** [comment]
@wojtek0806 @jasonrahm this PR is mergable. I just updated it to rebase on the upstream code. So feel free to merge whenever you want

**Comment by jasonrahm** [comment]
reviewing now

**Review by jasonrahm — APPROVED** [review]
lgtm

**Comment by caphrim007** [comment]
@jasonrahm merge with reckless abandon

**Pull request merged**
