### PR TITLE
Adding ASM filemixin

### PR DESCRIPTION
**Pull request by wojtek0806**
#700

Problem:
This is first of a series of PRs aimed at implementing ASM endpoint. This is a first phase of implementation. This PR adds mixin class that will be later used with file-transfer endpoint for ASM.

Analysis:
Added AsmFileTransfer mixin to mixins.py

Tests:
none

### CODE REVIEW

**Comment by wojtek0806** [comment]
@zancas

**Comment by caphrim007** [comment]
Can you elaborate on your "ease of code maintenance" thoughts?

**Comment by wojtek0806** [comment]
if there is need to change/update that part of code relating to ASM file-transfer you can modify the mixin, without affecting other parts of the SDK, I was considering making this mixin inherit from FileUploadMixin, but the whole point of mixins is that they are helper classes they should not inherit from anything than the meta_class

**Comment by caphrim007** [comment]
Do you see a definite discrepancy that you're working around? Or is this just theory right now?

**Comment by wojtek0806** [comment]
no theory, this was already tested, the code is ready for asm, just adding this gradually, and writing unit and functional tests as appropriate

**Comment by wojtek0806** [comment]
have a look for the full code in PR #699

**Pull request closed without merging**
