### PR TITLE
Adding files to build RPMs and deploy them to github

### PR DESCRIPTION
**Pull request by richbrowne**
@mattgreene @jlongstaf 

Adding packaging logic.

### CODE REVIEW

**Comment by richbrowne** [comment]
@mattgreene @jlongstaf @zancas @swormke 

Adding packaging logic.

**Comment by richbrowne** [comment]
This was reviewed by Matt, but we don't have the permissions to merge.

**Comment by richbrowne** [comment]
Adding the Debian packaging to this.

**Comment by mattgreene** [comment]
Looks ok to me.  @pjbreaux or @jlongstaf will need to accept the PR.

**Comment by zancas** [comment]
I reset development to `abab879d8ec00d7987936788d935a9ba66f14341`.

For three reasons:

1)  We strive to not merge our own PRs.
2)  We don't want a "rail-yard" of commit histories merging into development, so we generally rebase our feature branches on development immediately before merging.
3)  I'm not clear on the trade-offs between security and convenience we get from having "secure" api tokens in our .travis.yml.

**Pull request merged**
