### PR TITLE
Adds api for smtp-server

### LINKED ISSUE #1363: add api for smtp-server
missing from the sdk

tm/sys/smtp-server

### PR DESCRIPTION
**Pull request by caphrim007**
Issues:
Fixes #1363

Problem:
The smtp-server API was not in the SDK

Analysis:
This adds it

Tests:
functional

### CODE REVIEW

**Comment by jasonrahm** [comment]
Looks good minus the docs api endpoint, but i can add that with the other two security endpoints i have noted

**Comment by caphrim007** [comment]
@jasonrahm what?

**Comment by caphrim007** [comment]
Can't set status; build succeeded.

**Comment by caphrim007** [comment]
do not merge

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build succeeded.

**Pull request merged**
