### PR TITLE
Feature.modify 609

### PR DESCRIPTION
**Pull request by pjbreaux**
@zancas 
#### What's this change do?

Implements the modify method, which is a requests.patch call to exclusively update that which a user specifies by sending in the keyword arguments. The arguments are those that are updated, and nothing more.
#### Where should the reviewer start?

Start at the unit and functional tests, then move on to resource.py changes.

### CODE REVIEW

**Comment by pjbreaux** [comment]
@zancas: check out the failure in jenkins for the 11.6.0 run. This test doesn't fail for me locally, when testing against 12.0.0

**Comment by zancas** [comment]
Is there still a 11.6.0 Jenkins fail?   This PR shows "All checks have passed".

**Comment by zancas** [comment]
@pjbreaux I ran the tests locally, 11.6.0:

`442 passed, 37 skipped in 109.24 seconds`

The skips are mostly `gtm`.

I have some unittests on my version of the feature branch:

`feature.unittest_modify_609`

So, can you either rebase on top of it, or otherwise get it to be the thing this PR is to include it?

**Comment by pjbreaux** [comment]
Rebased and pushed.

**Pull request merged**
