### PR TITLE
Feature.remote auth endpoints

### LINKED ISSUE #1120: Add mgmt/tm/auth provider endpoints
radius, ldap, tacacs all missing

### PR DESCRIPTION
**Pull request by jasonrahm**
Adding Remote Auth endpoints

- Fixes #1120 will close the issue on commit to repo

Describe the issue that this change addresses
- Problem: endpoints didn't exist.

Describe the change itself and why you made the changes you did
- Analysis: this PR adds the missing endpoints

Describe the tests you ran and/or created to test this change
- Tests:
 Functional and Unit tests

### CODE REVIEW

**Comment by jasonrahm** [comment]
@caphrim007 or @wojtek0806, this PR is ready for review.

**Comment by wojtek0806** [comment]
Can you squish the commits please ? @jasonrahm

**Comment by jasonrahm** [comment]
@wojtek0806 done

**Comment by wojtek0806** [comment]
I have put a comment in @jasonrahm

**Pull request merged**
