### PR TITLE
Update cryptography package

### PR DESCRIPTION
**Pull request by sravyap135**

### CODE REVIEW

**Comment by zhaoqin-github** [comment]
@sravyap135 Would you please restart your check?

**Comment by sravyap135** [comment]
@zhaoqin-github, Observing error when trying to restart : `An error occurred. The job could not be restarted.`
image

**Comment by zhaoqin-github** [comment]
@sravyap135 I am not sure what is wrong in Travis... You may use ```git commit --amend``` to generate a new commit id and push it again. Travis should trigger a new build.

**Comment by zhaoqin-github** [comment]
@sravyap135 The failure in your latest check should be fixed by https://github.com/F5Networks/f5-common-python/pull/1576/commits/bfd2bac2a9755a7f8e67c60c38f48dcf0ed40c19

Let me merge it first, and your check should be fine after a rebase.

**Comment by zhaoqin-github** [comment]
@sravyap135 The ci in development branch is OK now. Please rebase your branch. Thank you!

**Comment by sravyap135** [comment]
@zhaoqin-github  Job succeeds for python 2.7, 3.5 and fails for python 3.6 with error `could not install deps [-rrequirements.test.txt, git+https://github.com/F5Networks/f5-icontrol-rest-python.git@1.0]`

**Comment by zhaoqin-github** [comment]
> @zhaoqin-github Job succeeds for python 2.7, 3.5 and fails for python 3.6 with error `could not install deps [-rrequirements.test.txt, git+https://github.com/F5Networks/f5-icontrol-rest-python.git@1.0]`

I am not quite sure, but this error is listed here https://cryptography.io/en/latest/faq/#installing-cryptography-fails-with-error-can-not-find-rust-compiler

The CI build in development branch can pass without you code change. That indicates your code change might not be compatible with every python version. Maybe you can switch to another version of cryptography, for example version 3.3.2, and have a try.

**Comment by sravyap135** [comment]
Thanks @zhaoqin-github, It worked !

**Pull request merged**
