### PR TITLE
Adding tm/util/unix-rm

### PR DESCRIPTION
**Pull request by jasonrahm**
Issue #538 - Feature introduction for utility commands; unix-rm up first.

Updated Files:
f5/bigip/tm/**init**.py

Added Files:
f5/bigip/tm/util/**init**.py
f5/bigip/tm/util/Unix_Rm.py
f5/bigip/tm/test/test_unix_rm.py
test/functional/tm/util/**init**.py (empty file)
test/functional/tm/util/test_unix_rm.py

### CODE REVIEW

**Comment by jasonrahm** [comment]
successful tests on first try...what?!?

@caphrim007 or @zancas, this is ready for review. Happy to answer any questions.

**Comment by jasonrahm** [comment]
(lion king mood music) Can you feel...the _merge_ tonight, it is where we are....

:) Have a nice weekend all.

**Comment by caphrim007** [comment]
@jasonrahm would you add tests to cover the red lines in this coverage report?

https://coveralls.io/builds/7825345/source?filename=f5%2Fbigip%2Ftm%2Futil%2FUnix_Rm.py

**Comment by caphrim007** [comment]
hakuna matata, what a wonder PR

**Pull request merged**
