### PR TITLE
Protocol Inspection - Profile, Compliance, Signature

### PR DESCRIPTION
**Pull request by hemantsk**
Analysis: 
Protocol Inspection Profiles, Signatures can be added/modified. Also, the list of compliances can be obtained

Tests:
Functional and unit tests for the above features have been added.

### CODE REVIEW

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
this PR needs to be rebased on top of current development. Please remove the merge-commit as well.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by hemantsk** [comment]
Not sure why build failed. Rebased it on top and resolved conflicts.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build failed.

**Comment by caphrim007** [comment]
Can't set status; build succeeded.

**Pull request merged**
