### PR TITLE
adding missing iFile tests

### PR DESCRIPTION
**Pull request by wojtek0806**
addresses part of #635

### CODE REVIEW

**Comment by caphrim007** [comment]
tested and working on
- 11.5.4 hf1
- 11.6.0
- 12.0.0
- 12.1.0 hf1

**Comment by zancas** [comment]
Hey folks, I see that this PR has merge conflicts.   Is someone looking into this?

**Comment by zancas** [comment]
This PR has 12! Files changed...    12!   That's a LOT!
Is that really necessary is this really several different PR-able features mixed together?

**Comment by jasonrahm** [comment]
I think what is happening here is that my ssl code, which was branched off my ifile code, was merged before the ifiles. I closed that PR since the code was included. This PR is to I don't think was intended to be merged, but rather to show some updated tests for ifiles, which I also need to look at for data groups. So...I think we need to submit updated test code for ifiles, ssl, and data_groups, but doesn't need to be all in this PR. Suggest a direction and we can close this PR and start fresh.

**Comment by zancas** [comment]
I've rebased the code associated with this PR on top of the current version of development.  I'm going to push it to a branch in my fork called `test_ifiles`.   Can you @jasonrahm please fetch that branch and see if it has code that can be broken into separate components?   It sounds to me like there's an `ifiles` component, an `ssl` component, and a `data_groups` component?  That seems like three separate features to me.

**Comment by zancas** [comment]
@jasonrahm after you fetch the above branch please close this PR and open 3 issues to track each of the components (unless those three components are not the right way to break up the code, in which case break it up the "right" way, and open the "right" issues as you see fit).

**Comment by zancas** [comment]
Let's try to land the smallest possible discrete feature first.

**Comment by jasonrahm** [comment]
The features I believe are already landed, this is all test cleanup/enhancement.

src: mobile

On Aug 22, 2016, at 5:28 PM, Za Wilgustus <notifications@github.com<mailto:notifications@github.com>> wrote:

Let's try to land the smallest possible discrete feature first.

##

**Comment by jasonrahm** [comment]
this PR can be closed now, all requisite code has been merged in other PRs

**Comment by caphrim007** [comment]
@jasonrahm  done

**Pull request closed without merging**
